version: "3.7"
services:
  postgres:
    container_name: postgresql-microservice
    image: postgres:16.1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
      PGDATA: /data/postgres
    volumes:
      - ./postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
  postgres: