server:
  port: 8082

spring:
  application:
    name: notification
  datasource:
    url: jdbc:postgresql://localhost:5432/notification
    username: postgres
    password: 12345678
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
  rabbitmq:
    template:
      exchange: internal.exchange
      default-receive-queue: notification.queue
      routing-key: internal.notification.routing-key
    username: rabbitmq
    password: rabbitmq
    addresses: localhost:5672


eureka:
  client:
    service-url:
      zone1: http://localhsot:8761/eureka
    fetch-registry: true
    register-with-eureka: true

management:
  tracing:
    sampling:
      probability: 1.0

