spring:
  application:
    name: eureka-server

server:
  port: 8761
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false

management:
  zipkin:
    tracing:
      endpoint: http://localhost:9411
  tracing:
    sampling:
      probability: 1.0
